### PR TITLE
Fix RuntimeError in `REXML::Parsers::BaseParser` for valid feeds

### LINKED ISSUE #198: RuntimeError "entity expansion has grown too large" with default entities in `REXML::Parsers::BaseParser` after 3.3.3
### Why?

We are using the [ruby/rss](https://github.com/ruby/rss) gem to parse XML feeds and we get RuntimeErrors “entity expansion has grown too large” since [rexml 3.3.3](https://github.com/ruby/rexml/releases/tag/v3.3.3) even though there is only [default entities](https://github.com/ruby/rexml/blob/e14847cee53d26eb162ad786ba12e3cd7a86fce0/lib/rexml/parsers/baseparser.rb#L120-L125) in the feeds.

### How to reproduce

Code:

```ruby
# rexml/refactor_entity_example.rb

$LOAD_PATH.unshift(File.expand_path("lib"))

require "rexml/parsers/baseparser"

valid_feed = "&lt;p&gt;#{'A' * 10_240}&lt;/p&gt;"

base_parser = REXML::Parsers::BaseParser.new("")
base_parser.unnormalize(valid_feed) # => "<p>" + "A" * 10_240 + "</p>"
```

Error:

```shell
❯ bundle exec ruby refactor_entity_example.rb
/Users/vikiv/repos/rexml/lib/rexml/parsers/baseparser.rb:558:in `block in unnormalize': entity expansion has grown too large (RuntimeError)
	from /Users/vikiv/repos/rexml/lib/rexml/parsers/baseparser.rb:551:in `each'
	from /Users/vikiv/repos/rexml/lib/rexml/parsers/baseparser.rb:551:in `unnormalize'
	from refactor_entity_example.rb:8:in `<main>'
```

### Suggestion  

I suggest we change `#entity`/`#unnormalize` to not raise the RuntimeError “entity expansion has grown too large” when the feed consists of only default entities. 

```diff
diff --git a/lib/rexml/parsers/baseparser.rb b/lib/rexml/parsers/baseparser.rb
index 342f948..d560d3a 100644
--- a/lib/rexml/parsers/baseparser.rb
+++ b/lib/rexml/parsers/baseparser.rb
@@ -505,15 +505,13 @@ module REXML
       private :pull_event

       def entity( reference, entities )
-        value = nil
         value = entities[ reference ] if entities
         if value
           record_entity_expansion
-        else
-          value = DEFAULT_ENTITIES[ reference ]
-          value = value[2] if value
+          return unnormalize( value, entities ) if value
         end
-        unnormalize( value, entities ) if value
+
+        nil
       end

       # Escapes all possible entities
```

### PR DESCRIPTION
**Pull request by vikiv480**
* Change `#entity` to not match against default entities

After this change, the following example will not raise a RuntimeError:

```ruby
# rexml/refactor_entity_example.rb

$LOAD_PATH.unshift(File.expand_path("lib"))

require "rexml/parsers/baseparser"

valid_feed = "&lt;p&gt;#{'A' * 10_240}&lt;/p&gt;"

base_parser = REXML::Parsers::BaseParser.new("")
base_parser.unnormalize(valid_feed) # => "<p>" + "A" * 10_240 + "</p>"
```

Default entities now gets substituted by this block instead

https://github.com/ruby/rexml/blob/e14847cee53d26eb162ad786ba12e3cd7a86fce0/lib/rexml/parsers/baseparser.rb#L560-L563

Close #198

### CODE REVIEW

File: lib/rexml/parsers/baseparser.rb [hunk 1]
```diff
@@ -505,15 +505,13 @@ def pull_event
       private :pull_event
 
       def entity( reference, entities )
-        value = nil
```
Comment (kou) [inline lib/rexml/parsers/baseparser.rb:508]: Could you revert this change for readability?
It shows that the default `value` is `nil` explicitly.

File: lib/rexml/parsers/baseparser.rb [hunk 2]
```diff
@@ -505,15 +505,13 @@ def pull_event
...
         value = entities[ reference ] if entities
         if value
           record_entity_expansion
-        else
-          value = DEFAULT_ENTITIES[ reference ]
-          value = value[2] if value
+          return unnormalize( value, entities ) if value
```
Comment (kou) [inline lib/rexml/parsers/baseparser.rb:511]: Do we need this `if value`?

**Review by kou — COMMENTED** [review]
Could you add a test for this case?

**Comment by kou** [comment]
@naitoh Could you review this?

File: lib/rexml/parsers/baseparser.rb (hunk 1 above)
Comment (vikiv480) [reply lib/rexml/parsers/baseparser.rb]: Okay, I reverted the change in [b5da207](https://github.com/ruby/rexml/pull/199/commits/b5da2078bc7e7c6331ed3f7d8369a052d172c5fe)

File: lib/rexml/parsers/baseparser.rb (hunk 2 above)
Comment (vikiv480) [reply lib/rexml/parsers/baseparser.rb]: No, you are right, it's unnecessary. Removed it in [b5da207](https://github.com/ruby/rexml/pull/199/commits/b5da2078bc7e7c6331ed3f7d8369a052d172c5fe)

**Comment by vikiv480** [comment]
>Could you add a test for this case?

I've added some tests in [6555c27](https://github.com/ruby/rexml/pull/199/commits/6555c279faf61b83bb5af204051f05bf1684ec0a), let me know what you think.

**Comment by naitoh** [comment]
> Could you review this?

## before (This PR)
```ruby
      def entity( reference, entities )
        value = nil
        value = entities[ reference ] if entities
        if value
          record_entity_expansion
          return unnormalize( value, entities )
        end

        nil
      end
```

- If `entities == nil`, the return value is nil because value is always nil. 
- If `value == nil`, the return value is nil, so an early return is easier to understand.

## after
```ruby
      def entity( reference, entities )
        return unless entities

        value = entities[ reference ]
        return if value.nil?

        record_entity_expansion
        unnormalize( value, entities )
      end
```

Thanks.

**Comment by vikiv480** [comment]
@naitoh Thanks for the suggestion, I like the change 👍 60632a5

File: test/test_stream.rb [hunk 3]
```diff
@@ -89,6 +89,44 @@ def entity(content)
...
+    end
+
+    def teardown
+      REXML::Security.entity_expansion_limit = @default_entity_expansion_limit
+      REXML::Security.entity_expansion_text_limit = @default_entity_expansion_text_limit
+    end
+
+    def test_with_only_default_entities
+      member_value = "&lt;p&gt;#{'A' * @default_entity_expansion_text_limit}&lt;/p&gt;"
+      source = StringIO.new(<<-XML)
```
Comment (naitoh) [inline test/test_stream.rb:105]:
```suggestion
      source = <<-XML
```
I think StringIO.new is unnecessary.

**Review by naitoh — COMMENTED** [review]
Additional review.

File: test/test_stream.rb (hunk 3 above)
Comment (vikiv480) [reply test/test_stream.rb]: Fixed in [b7e9378](https://github.com/ruby/rexml/pull/199/commits/b7e937898847d4ab938ade808f57e47a1d08975e)

**Comment by naitoh** [comment]
I have checked this PR.
I think this PR is good.
Thanks!

File: test/test_stream.rb [hunk 4]
```diff
@@ -89,6 +89,44 @@ def entity(content)
...
+      REXML::Document.parse_stream(source, listener)
+
+      expected_value = "<p>#{'A' * @default_entity_expansion_text_limit}</p>"
+      assert_equal(expected_value, listener.text_value.strip)
+      assert do
+        listener.text_value.bytesize > @default_entity_expansion_text_limit
+      end
+    end
+  end
+
```
Comment (kou) [inline test/test_stream.rb:129]:
```suggestion
```

**Comment by kou** [comment]
Thanks.
