### PR TITLE
Reject unclosed DOCTYPE on parsing

### LINKED ISSUE #152: BUG: REXML accepts unclosed DOCTYPE
Currently, REXML accepts unclosed DOCTYPE declarations.

```ruby
require "rexml/document"

REXML::Document.new("<!DOCTYPE foo [")
# => <UNDEFINED> ... </>
# No exceptions are raised!
```

It seems strange and it should be fixed.

### PR DESCRIPTION
**Pull request by makenowjust**
Fix #152

### CODE REVIEW

File: test/parse/test_document_type_declaration.rb [hunk 1]
```diff
@@ -53,6 +53,53 @@ def test_no_name
       end
     end
 
+    class TestUnclosed < self
+      def test_unclosed_doctype_only
```
Comment (kou) [inline test/parse/test_document_type_declaration.rb:57]: `unclosed_doctype_` is redundant because file name is `test_document_type_declaration.rb` and class name is `TestUnclosed`.

```suggestion
      def test_no_extra_node
```

File: lib/rexml/parsers/treeparser.rb [hunk 2]
```diff
@@ -24,12 +24,20 @@ def parse
             #STDERR.puts "TREEPARSER GOT #{event.inspect}"
             case event[0]
             when :end_document
+              if in_doctype
+                raise ParseException.new("Malformed DOCTYPE: unclosed",
+                                         @parser.source, @parser)
+              end
```
Comment (kou) [inline lib/rexml/parsers/treeparser.rb:30]: Can we do this in `baseparser.rb` instead of here?
If we can do it, other parsers such as `StreamParser` can detect this case.

Comment (makenowjust) [reply lib/rexml/parsers/treeparser.rb:30]: I will try it.

Comment (makenowjust) [reply lib/rexml/parsers/treeparser.rb]: Updated!
